version: "3"
services:
  nginx:
    ports: 
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MYSQL_DB_NAME=teams
      - MYSQL_HOST=db
    command: npm start


