version: "3"
services:
  nginx:
    ports: 
      - "80:80"
  node-app:
    image: nyihtut007/nodeapp
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MYSQL_DB_NAME=teams
      - MYSQL_HOST=db
    command: npm start


