version: "3"
services:
  nginx:
    ports: 
      - "80:80"
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: production 
    environment:
      - NODE_ENV=production
      - MYSQL_DB_NAME=teams
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=ZinZinn@@7
    command: npm start
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ZinZinn@@7